# Generated by Django 3.2 on 2025-12-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='batch_id',
            field=models.CharField(max_length=100),
        ),
    ]
