# Generated by Django 3.2 on 2026-01-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_alter_tracker_batch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='grade',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
