# Generated by Django 3.2 on 2026-02-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0005_auto_20260107_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='gps_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='gps_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='package_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='previous_stage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='variety',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
