# Generated by Django 3.2 on 2026-02-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0006_auto_20260203_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tracker',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='tracker',
            name='batch_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='block_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='gps_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='gps_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
    ]
