# Generated by Django 3.2 on 2025-12-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=100, unique=True)),
                ('fruit_type', models.CharField(max_length=50)),
                ('quantity_kg', models.FloatField()),
                ('stage', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('handled_by', models.CharField(max_length=50)),
                ('block_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tracker',
            index=models.Index(fields=['batch_id'], name='track_track_batch_i_e12ef0_idx'),
        ),
    ]
