# Generated by Django 3.2 on 2026-01-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_tracker_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='gps_latitude',
            field=models.DecimalField(decimal_places=6, max_digits=10, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tracker',
            name='gps_longitude',
            field=models.DecimalField(decimal_places=6, max_digits=10, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tracker',
            name='previous_stage',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
