# Generated by Django 3.2 on 2026-01-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_auto_20260105_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='package_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tracker',
            name='variety',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
