# Generated by Django 3.2 on 2026-02-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0007_auto_20260205_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tracker',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='tracker',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tracker',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tracker',
            name='verified_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='batch_id',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='block_hash',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='gps_latitude',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='gps_longitude',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='grade',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='handled_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='package_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='previous_stage',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='variety',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
